-- 1. Tabla de Torneos
create table tournaments (
  id uuid default gen_random_uuid() primary key,
  name text not null, -- Ej: "Copa Mundial de la FIFA 2026"
  year integer not null,
  is_active boolean default false
);

-- 2. Tabla de Fases del Torneo
create table tournament_stages (
  id uuid default gen_random_uuid() primary key,
  tournament_id uuid references tournaments(id) on delete cascade,
  stage_key text not null, -- 'OCTAVOS', 'CUARTOS', 'SEMIFINAL', 'FINAL'
  display_name text not null,
  sequence_order integer not null
);

-- 3. Tabla de Equipos / Selecciones
create table teams (
  id text primary key, -- Código ISO (Ej: 'VEN', 'ARG', 'FRA')
  name text not null,
  flag_url text not null
);

-- 4. Tabla de Perfiles de Usuario
create table profiles (
  id uuid references auth.users on delete cascade primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  total_points integer default 0,
  is_admin boolean default false
);

-- 5. Tabla de Partidos (Con punteros para armar el Bracket dinámicamente)
create table matches (
  id bigint generated by default as identity primary key,
  stage_id uuid references tournament_stages(id) on delete cascade,
  team_home_id text references teams(id),
  team_away_id text references teams(id),
  match_time timestamp with time zone not null, -- Guardado estrictamente en UTC
  goals_home integer default null,
  goals_away integer default null,
  winner_id text references teams(id) default null,
  is_finished boolean default false,
  bracket_match_number integer, -- ID visual del nodo en el organigrama
  next_match_id bigint references matches(id) -- Siguiente partido al que avanza el ganador
);

-- 6. Tabla de Predicciones
create table predictions (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  match_id bigint references matches(id) on delete cascade not null,
  pred_goals_home integer not null,
  pred_goals_away integer not null,
  pred_winner_id text references teams(id),
  points_earned integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, match_id)
);

-- 7. Log de Auditoría (Anti-Fraude y soporte técnico)
create table audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id),
  action text not null, -- Ej: 'CREATE_PREDICTION', 'UPDATE_PREDICTION'
  details jsonb,
  ip_address text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Indices para optimizar rendimiento
create index if not exists predictions_user_match_idx on predictions(user_id, match_id);
create index if not exists profiles_points_idx on profiles(total_points desc);

-- Políticas RLS (Row Level Security) básicas
alter table tournaments enable row level security;
alter table tournament_stages enable row level security;
alter table teams enable row level security;
alter table profiles enable row level security;
alter table matches enable row level security;
alter table predictions enable row level security;
alter table audit_logs enable row level security;

-- Políticas de lectura pública para datos del torneo
create policy "Torneos públicos" on tournaments for select using (true);
create policy "Fases públicas" on tournament_stages for select using (true);
create policy "Equipos públicos" on teams for select using (true);
create policy "Partidos públicos" on matches for select using (true);
create policy "Perfiles públicos (Leaderboard)" on profiles for select using (true);

-- Política para las predicciones: Los usuarios pueden ver todas las predicciones (para ver el leaderboard), pero solo insertar/modificar las suyas
create policy "Predicciones públicas" on predictions for select using (true);
create policy "Insertar predicciones propias" on predictions for insert with check (auth.uid() = user_id);
create policy "Actualizar predicciones propias" on predictions for update using (auth.uid() = user_id);

-- Función RPC para recalcular puntos y finalizar partido
create or replace function finalize_match(
  match_id_param bigint,
  actual_goals_home integer,
  actual_goals_away integer,
  actual_winner_id text
)
returns void
language plpgsql
security definer
as $$
declare
  pred record;
  earned integer;
begin
  -- 1. Actualizar el partido con el resultado real
  update matches 
  set 
    goals_home = actual_goals_home,
    goals_away = actual_goals_away,
    winner_id = actual_winner_id,
    is_finished = true
  where id = match_id_param;

  -- 2. Recorrer todas las predicciones de este partido y calcular puntos
  for pred in (select * from predictions where match_id = match_id_param) loop
    earned := 0;

    -- A. Marcador exacto: 3 puntos
    if (pred.pred_goals_home = actual_goals_home and pred.pred_goals_away = actual_goals_away) then
      earned := earned + 3;
    
    -- B. Acertar al ganador o empate: 1 punto (solo si no acertó exacto)
    else
      -- Gana Local
      if (actual_goals_home > actual_goals_away and pred.pred_goals_home > pred.pred_goals_away) then
        earned := earned + 1;
      -- Gana Visitante
      elsif (actual_goals_home < actual_goals_away and pred.pred_goals_home < pred.pred_goals_away) then
        earned := earned + 1;
      -- Empate
      elsif (actual_goals_home = actual_goals_away and pred.pred_goals_home = pred.pred_goals_away) then
        earned := earned + 1;
      end if;
    end if;

    -- C. Acertar quién clasifica en caso de empate
    if (actual_goals_home = actual_goals_away and actual_winner_id is not null) then
      if (pred.pred_winner_id = actual_winner_id) then
        earned := earned + 1;
      end if;
    end if;

    -- D. Guardar puntos en la predicción
    update predictions 
    set points_earned = earned 
    where id = pred.id;

    -- E. Sumar puntos al perfil del usuario
    update profiles 
    set total_points = total_points + earned 
    where id = pred.user_id;

  end loop;
end;
$$;
